name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: '0 0 * * *'  # Todos los días a la medianoche
  workflow_dispatch:      # Permite ejecutarlo manualmente desde GitHub

jobs:
  generate-3d-contrib:
    runs-on: ubuntu-latest
    name: Generar gráfico 3D de contribuciones

    permissions:
      contents: write  # Necesario para poder hacer commit en el repo

    steps:
      - uses: actions/checkout@v3

      - name: Ejecutar generador 3D (fork de yoshi389111)
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Subir imagen generada al repo
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add profile-3d-contrib/**.svg
          git commit -m "Actualizar imagen 3D de contribuciones" || echo "Sin cambios"
          git push
